package com.Dragon.Kassel.pro;

public class School {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column School.s_id
     *
     * @mbggenerated Fri Aug 19 21:39:22 CST 2022
     */
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column School.s_dept
     *
     * @mbggenerated Fri Aug 19 21:39:22 CST 2022
     */
    private String sDept;

    @Override
    public String toString() {
        return "School{" +
                "sId=" + sId +
                ", sDept='" + sDept + '\'' +
                '}';
    }

    public School() {
    }

    public School(Integer sId, String sDept) {
        this.sId = sId;
        this.sDept = sDept;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column School.s_id
     *
     * @return the value of School.s_id
     *
     * @mbggenerated Fri Aug 19 21:39:22 CST 2022
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column School.s_id
     *
     * @param sId the value for School.s_id
     *
     * @mbggenerated Fri Aug 19 21:39:22 CST 2022
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column School.s_dept
     *
     * @return the value of School.s_dept
     *
     * @mbggenerated Fri Aug 19 21:39:22 CST 2022
     */
    public String getsDept() {
        return sDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column School.s_dept
     *
     * @param sDept the value for School.s_dept
     *
     * @mbggenerated Fri Aug 19 21:39:22 CST 2022
     */
    public void setsDept(String sDept) {
        this.sDept = sDept == null ? null : sDept.trim();
    }
}