package com.Dragon.Kassel.pro;

public class Student {

    public Student(String sName, String sBlood, String sDep) {
        this.sName = sName;
        this.sBlood = sBlood;
        this.sDep = sDep;
    }

    public Student() {
    }

    @Override
    public String toString() {
        return "Student{" +
                "sName='" + sName + '\'' +
                ", sId=" + sId +
                ", sBlood='" + sBlood + '\'' +
                ", sDep='" + sDep + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.s_name
     *
     * @mbggenerated Tue Aug 23 23:06:05 CST 2022
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.s_id
     *
     * @mbggenerated Tue Aug 23 23:06:05 CST 2022
     */
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.s_blood
     *
     * @mbggenerated Tue Aug 23 23:06:05 CST 2022
     */
    private String sBlood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.s_dep
     *
     * @mbggenerated Tue Aug 23 23:06:05 CST 2022
     */
    private String sDep;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.s_name
     *
     * @return the value of Student.s_name
     *
     * @mbggenerated Tue Aug 23 23:06:05 CST 2022
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.s_name
     *
     * @param sName the value for Student.s_name
     *
     * @mbggenerated Tue Aug 23 23:06:05 CST 2022
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.s_id
     *
     * @return the value of Student.s_id
     *
     * @mbggenerated Tue Aug 23 23:06:05 CST 2022
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.s_id
     *
     * @param sId the value for Student.s_id
     *
     * @mbggenerated Tue Aug 23 23:06:05 CST 2022
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.s_blood
     *
     * @return the value of Student.s_blood
     *
     * @mbggenerated Tue Aug 23 23:06:05 CST 2022
     */
    public String getsBlood() {
        return sBlood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.s_blood
     *
     * @param sBlood the value for Student.s_blood
     *
     * @mbggenerated Tue Aug 23 23:06:05 CST 2022
     */
    public void setsBlood(String sBlood) {
        this.sBlood = sBlood == null ? null : sBlood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.s_dep
     *
     * @return the value of Student.s_dep
     *
     * @mbggenerated Tue Aug 23 23:06:05 CST 2022
     */
    public String getsDep() {
        return sDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.s_dep
     *
     * @param sDep the value for Student.s_dep
     *
     * @mbggenerated Tue Aug 23 23:06:05 CST 2022
     */
    public void setsDep(String sDep) {
        this.sDep = sDep == null ? null : sDep.trim();
    }
}